export const ADD_QUESTION_LIST = 'ADD_QUESTION_LIST';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const SET_RATINGS = 'SET_RATINGS';
export const SET_CHARACTERISTICS = 'SET_CHARACTERISTICS';
export const SET_TOTAL_REVIEWS = 'SET_TOTAL_REVIEWS';
export const SET_REVIEW_LIST = 'SET_REVIEW_LIST';
export const SET_PRODUCT_IMAGE_INFO = 'GET_PRODUCT_IMAGE';
export const SEARCH_QUESTIONS = 'SEARCH_QUESTIONS'